server:
  port: 8900

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/home_decor
    username: root
    password: mariadb
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.decormasters.homedecor.domain
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    com:
      decormasters:
        homedecor: debug

file:
  upload:
    location: ${user.home}/home-decor/uploads/

jwt:
  secret-key: # 토근 발급시와 토근 위조 검사시 사용할 서명
  access-token-validity-time: 3600000  # 1시간
  refresh-token-validity-time: 604800000 # 7일
