server:
  port: 8900

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/home_decor
    username: root
    password: mariadb
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.decormasters.homedecor.domain
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    com:
      decormasters:
        homedecor: debug

file:
  upload:
    location: ${user.home}/home-decor/uploads/

jwt:
  # jwt 토큰 위조 방지를 확인할 수 있는 부분인 signature 부분에서 사용할 값.
  # 만드는 방법 : SecureRandom 이라고 검색하여 확인 가능
  secret-key: TN21vvHuO3qoy9pHYInUDrD6ijJBdm+PWx24I/zwl6s=
  access-token-validity-time: 3600000  # 1시간 (ms)
  refresh-token-validity-time: 604800000 # 7일 (ms)
